Vagrant.configure("2") do |config|
  config.disksize.size = '100GB'
  config.ssh.shell="/bin/sh"
  config.vm.box = "freebsd/FreeBSD-12.0-CURRENT"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
end
