#ifndef PROTOCOL_COMMON_H
#define PROTOCOL_COMMON_H

#define MESSAGE_HOLDER_SIZE 1500
#include "../headers/caml_common.h"
#include "../headers/protocol.h"

static int MESSAGESETSIZE_FIELD_SIZE= 12;
static int NUM_SOR_FIELD_SIZE= 12;
static int NUM_PARTITIONS_FIELD_SIZE= 12;
static int NUM_PARTS_FIELD_SIZE= 12;
static int GROUP_COORDINATOR_REQUEST_SIZE_FIELD_SIZE= 4;
static int SSPR_SIZE_FIELD_SIZE= 4;
static int METADATA_SIZE_FIELD_SIZE= 4;
static int APIKEY_FIELD_SIZE= 12;
static int TOPICERRORCODE_FIELD_SIZE= 12;
static int REPLICAS_SIZE_FIELD_SIZE= 4;
static int CONSUMERGROUPGENERATIONID_FIELD_SIZE= 12;
static int HOST_SIZE_FIELD_SIZE= 4;
static int THROTTLETIME_FIELD_SIZE= 12;
static int NUM_SUB_OFR_FIELD_SIZE= 12;
static int NUM_SUBSUB_FIELD_SIZE= 12;
static int CORRDINATORID_FIELD_SIZE= 12;
static int NUM_REPLICAS_FIELD_SIZE= 12;
static int NUM_BROKERS_FIELD_SIZE= 12;
static int ATTRIBUTES_FIELD_SIZE= 12;
static int NUM_SFR_FIELD_SIZE= 12;
static int FETCHOFFSET_FIELD_SIZE= 16;
static int MAXBYTES_FIELD_SIZE= 12;
static int REPLICA_FIELD_SIZE= 12;
static int SOFR_SIZE_FIELD_SIZE= 4;
static int FETCH_RESPONSE_SIZE_FIELD_SIZE= 4;
static int NUM_SUB_FIELD_SIZE= 12;
static int APIVERSION_FIELD_SIZE= 12;
static int CRC_FIELD_SIZE= 16;
static int VALUE_SIZE_FIELD_SIZE= 4;
static int NUM_ISRS_FIELD_SIZE= 12;
static int RM_SIZE_FIELD_SIZE= 4;
static int CORRELATIONID_FIELD_SIZE= 12;
static int NUM_TOPICS_FIELD_SIZE= 12;
static int REPOLICAID_FIELD_SIZE= 12;
static int OFFSET_COMMIT_RESPONSE_SIZE_FIELD_SIZE= 4;
static int PARTITION_FIELD_SIZE= 12;
static int OFFSET_REQUEST_SIZE_FIELD_SIZE= 4;
static int KEY_SIZE_FIELD_SIZE= 4;
static int MESSAGESIZE_FIELD_SIZE= 12;
static int OFFSET_RESPONSE_SIZE_FIELD_SIZE= 4;
static int MESSAGE_SIZE_FIELD_SIZE= 4;
static int TOPICNAME_SIZE_FIELD_SIZE= 4;
static int PARTITIONID_FIELD_SIZE= 12;
static int REPLICAID_FIELD_SIZE= 12;
static int SOR_SIZE_FIELD_SIZE= 4;
static int OFFSET_COMMIT_REQUEST_SIZE_FIELD_SIZE= 4;
static int LEADER_FIELD_SIZE= 12;
static int OFFSET_FETCH_REQUEST_SIZE_FIELD_SIZE= 4;
static int PARTITIONMETADATAS_SIZE_FIELD_SIZE= 4;
static int TIMESTAMP_FIELD_SIZE= 16;
static int NUM_OFFSETS_FIELD_SIZE= 12;
static int ERRORCODE_FIELD_SIZE= 12;
static int CONSUMERID_FIELD_SIZE= 12;
static int BROKERS_SIZE_FIELD_SIZE= 4;
static int OFFSET_FIELD_SIZE= 16;
static int SOCR_SIZE_FIELD_SIZE= 4;
static int CORRDINATORPORT_FIELD_SIZE= 12;
static int NUM_SSOCR_FIELD_SIZE= 12;
static int SSOFR_SIZE_FIELD_SIZE= 4;
static int METADATA_RESPONSE_SIZE_FIELD_SIZE= 4;
static int MAXWAITTIME_FIELD_SIZE= 12;
static int TIMEOUT_FIELD_SIZE= 12;
static int TIME_FIELD_SIZE= 16;
static int CONSUMERGROUPID_SIZE_FIELD_SIZE= 4;
static int MESSAGESET_SIZE_FIELD_SIZE= 4;
static int ELEMS_SIZE_FIELD_SIZE= 4;
static int NUM_SUB_OCR_FIELD_SIZE= 12;
static int PARTITIONOFFSETS_SIZE_FIELD_SIZE= 4;
static int PRODUCE_RESPONSE_SIZE_FIELD_SIZE= 4;
static int SSFR_SIZE_FIELD_SIZE= 4;
static int PRODUCE_REQUEST_SIZE_FIELD_SIZE= 4;
static int SSOCR_SIZE_FIELD_SIZE= 4;
static int NUM_ELEMS_FIELD_SIZE= 12;
static int SPR_SIZE_FIELD_SIZE= 4;
static int CLIENTID_SIZE_FIELD_SIZE= 4;
static int METADATA_REQUEST_SIZE_FIELD_SIZE= 4;
static int NUM_SSOFR_FIELD_SIZE= 12;
static int MSET_SIZE_FIELD_SIZE= 4;
static int HIGHWAYMARKOFFSET_FIELD_SIZE= 16;
static int TOPICNAMES_SIZE_FIELD_SIZE= 4;
static int OFFSETS_SIZE_FIELD_SIZE= 4;
static int REQUIREDACKS_FIELD_SIZE= 12;
static int FETCH_REQUEST_SIZE_FIELD_SIZE= 4;
static int CORRDINATORHOST_SIZE_FIELD_SIZE= 4;
static int GROUP_COORDINATOR_RESPONSE_SIZE_FIELD_SIZE= 4;
static int ISR_FIELD_SIZE= 12;
static int SFR_SIZE_FIELD_SIZE= 4;
static int NODEID_FIELD_SIZE= 12;
static int GROUPID_SIZE_FIELD_SIZE= 4;
static int NUM_SSFR_FIELD_SIZE= 12;
static int MINBYTES_FIELD_SIZE= 12;
static int OFFSET_FETCH_RESPONSE_SIZE_FIELD_SIZE= 4;
static int PARTITIONERRORCODE_FIELD_SIZE= 12;
static int PORT_FIELD_SIZE= 12;

struct message_holder{
    char buf[MESSAGE_HOLDER_SIZE];
    int fd;
};

correlationId_t get_corrid(char *beg);
void build_req(struct RequestMessage* rq, enum request_type rt, int correlationId, char* clientId, va_list varlist);

#endif
